#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  annotations:
#    kubernetes.io/ingress.class: haproxy
#  name: prometheus-ingress
#spec:
#  rules:
#  - host: zerotrust-prometheus-zasbdy.nrp-nautilus.io
#    http:
#      paths:
#      - backend:
#          service:
#            name: prometheus-svc
#            port:
#              number: 9090
#        path: /
#        pathType: Prefix
#  tls:
#  - hosts:
#    - zerotrust-prometheus-zasbdy.nrp-nautilus.io
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: prometheus-svc
#spec:
#  selector:
#    app.kubernetes.io/name: prometheus
#  ports:
#    - protocol: TCP
#      port: 9090
#      targetPort: 9090
#---
apiVersion: v1
kind: Service
metadata:
  name: ground-svc
spec:
  selector:
    app.kubernetes.io/name: ground
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: prometheus
#  labels:
#    app.kubernetes.io/name: prometheus
#    app: prometheus
#    tier: server
#spec:
#  containers:
#  - name: prometheus
#    image: zachs18/zerotrust-demo:prometheus-v1
#    imagePullPolicy: Always
#    ports:
#      - containerPort: 5000
#    env:
#    - name: server
#      value: "ground-svc.gpn-mizzou-scully.svc.cluster.local:5000"
##    - name: prometheus
##      value: "prometheus-svc.gpn-mizzou-scully.svc.cluster.local:9090"
#    - name: prometheus_push
#      value: "prometheus-prometheus-pushgateway.gpn-mizzou-scully.svc.cluster.local:9091"
#    - name: PYTHONUNBUFFERED
#      value: "1"
##    command:
##      - sh
##      - "-c"
##      - "echo sleeping && sleep 3600000"
---
apiVersion: v1
kind: Pod
metadata:
  name: ground
  labels:
    app.kubernetes.io/name: ground
    app: ground
    tier: server
spec:
  containers:
  - name: ground
    image: zachs18/zerotrust-demo:ground-v2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
    env:
    - name: server
      value: "ground-svc.gpn-mizzou-scully.svc.cluster.local:5000"
#    - name: prometheus
#      value: "prometheus-svc.gpn-mizzou-scully.svc.cluster.local:9090"
    - name: prometheus_push
      value: "prometheus-prometheus-pushgateway.gpn-mizzou-scully.svc.cluster.local:9091"
    - name: PYTHONUNBUFFERED
      value: "1"
#    command:
#      - sh
#      - "-c"
#      - "echo sleeping && sleep 3600000"
---
apiVersion: v1
kind: Service
metadata:
  name: ground-prometheus-svc
spec:
  selector:
    app.kubernetes.io/name: ground
  ports:
    - protocol: TCP
      port: 5090
      targetPort: 5090
---
apiVersion: v1
kind: Service
metadata:
  name: drone1-prometheus-svc
spec:
  selector:
    app.kubernetes.io/name: drone1
  ports:
    - protocol: TCP
      port: 5090
      targetPort: 5090
---
apiVersion: v1
kind: Service
metadata:
  name: drone2-prometheus-svc
spec:
  selector:
    app.kubernetes.io/name: drone2
  ports:
    - protocol: TCP
      port: 5090
      targetPort: 5090
---
apiVersion: v1
kind: Service
metadata:
  name: drone3-prometheus-svc
spec:
  selector:
    app.kubernetes.io/name: drone3
  ports:
    - protocol: TCP
      port: 5090
      targetPort: 5090
---
apiVersion: v1
kind: Service
metadata:
  name: drone4-prometheus-svc
spec:
  selector:
    app.kubernetes.io/name: drone4
  ports:
    - protocol: TCP
      port: 5090
      targetPort: 5090
---
apiVersion: v1
kind: Pod
metadata:
  name: drone1
  labels:
    app.kubernetes.io/name: drone1
    app: drone1
    mission: sense
spec:
  containers:
  - name: drone1
    image: zachs18/zerotrust-demo:drone-v1
    imagePullPolicy: Always
    env:
    - name: server
      value: "ground-svc.gpn-mizzou-scully.svc.cluster.local:5000"
#    - name: prometheus
#      value: "prometheus-svc.gpn-mizzou-scully.svc.cluster.local:9090"
    - name: prometheus_push
      value: "prometheus-prometheus-pushgateway.gpn-mizzou-scully.svc.cluster.local:9091"
    - name: PYTHONUNBUFFERED
      value: "1"
#    command:
#      - sh
#      - "-c"
#      - "echo sleeping && sleep 3600000"
---
apiVersion: v1
kind: Pod
metadata:
  name: drone2
  labels:
    app.kubernetes.io/name: drone2
    app: drone2
    mission: sense
spec:
  containers:
  - name: drone2
    image: zachs18/zerotrust-demo:drone-v1
    imagePullPolicy: Always
    env:
    - name: server
      value: "ground-svc.gpn-mizzou-scully.svc.cluster.local:5000"
#    - name: prometheus
#      value: "prometheus-svc.gpn-mizzou-scully.svc.cluster.local:9090"
    - name: prometheus_push
      value: "prometheus-prometheus-pushgateway.gpn-mizzou-scully.svc.cluster.local:9091"
    - name: PYTHONUNBUFFERED
      value: "1"
#    command:
#      - sh
#      - "-c"
#      - "echo sleeping && sleep 3600000"
---
apiVersion: v1
kind: Pod
metadata:
  name: drone3
  labels:
    app.kubernetes.io/name: drone3
    app: drone3
    mission: sense
spec:
  containers:
  - name: drone3
    image: zachs18/zerotrust-demo:drone-v1
    imagePullPolicy: Always
    env:
    - name: server
      value: "ground-svc.gpn-mizzou-scully.svc.cluster.local:5000"
#    - name: prometheus
#      value: "prometheus-svc.gpn-mizzou-scully.svc.cluster.local:9090"
    - name: prometheus_push
      value: "prometheus-prometheus-pushgateway.gpn-mizzou-scully.svc.cluster.local:9091"
    - name: PYTHONUNBUFFERED
      value: "1"
#    command:
#      - sh
#      - "-c"
#      - "echo sleeping && sleep 3600000"
---
apiVersion: v1
kind: Pod
metadata:
  name: drone4
  labels:
    app.kubernetes.io/name: drone4
    app: drone4
    mission: sense
spec:
  containers:
  - name: drone4
    image: zachs18/zerotrust-demo:drone-v1
    imagePullPolicy: Always
    env:
    - name: server
      value: "ground-svc.gpn-mizzou-scully.svc.cluster.local:5000"
#    - name: prometheus
#      value: "prometheus-svc.gpn-mizzou-scully.svc.cluster.local:9090"
    - name: prometheus_push
      value: "prometheus-prometheus-pushgateway.gpn-mizzou-scully.svc.cluster.local:9091"
    - name: PYTHONUNBUFFERED
      value: "1"
#    command:
#      - sh
#      - "-c"
#      - "echo sleeping && sleep 3600000"
